hl.on("hyprland.start", function ()
    -- hyprbars buttons (config post-carga del plugin)
    hl.exec_cmd("hyprctl keyword plugin:hyprbars:hyprbars-button 'rgba(605f4aFF), 15, , hyprctl dispatch killactive, rgb(000000)'")
    hl.exec_cmd("hyprctl keyword plugin:hyprbars:hyprbars-button 'rgba(cac8adFF), 15, , hyprctl dispatch fullscreen 1, rgb(000000)'")
    hl.exec_cmd([[hyprctl keyword plugin:hyprbars:hyprbars-button 'rgba(cac8a5FF), 15, , if [[ $(hyprctl activewindow -j | jq -r ".workspace.name | startswith(\"special\")") == true ]]; then hyprctl -q dispatch togglespecialworkspace $(hyprctl activewindow -j | jq -r ".workspace.name" | sed "s/^special://"); else hyprctl -q dispatch movetoworkspacesilent special; fi, rgb(000000)']])

    hl.exec_cmd("steam -nochatui -nofriendsui -silent")
    hl.exec_cmd("solaar -w hide")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("sleep 1 && setxkbmap latam")
    hl.exec_cmd("linux-wallpaperengine --disable-mouse --scaling fill --silent --screen-root DP-2 --assets-dir /mnt/ssd/SteamLibrary/steamapps/common/wallpaper_engine/assets /mnt/ssd/SteamLibrary/steamapps/workshop/content/431960/2513410552")
end)
