# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
# exec-once = gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty 
# exec-once = gsettings set org.gnome.desktop.wm.preferences button-layout ":"
exec-once = steam -nochatui -nofriendsui -silent
exec-once = solaar -w hide
# exec-once = /usr/bin/kdeconnectd
exec-once = kdeconnect-indicator
exec-once = fcitx5
# exec-once = sleep 1 && setxkbmap latam
# exec-once = hyprpm reload
exec-once = linux-wallpaperengine --disable-mouse --scaling fill --silent --screen-root DP-2 --assets-dir /mnt/ssd/SteamLibrary/steamapps/common/wallpaper_engine/assets /mnt/ssd/SteamLibrary/steamapps/workshop/content/431960/2513410552
