-- Unbind upstream defaults que se reemplazan abajo
hl.unbind("SUPER + Period")
hl.unbind("SUPER + A")
hl.unbind("SUPER + B")
hl.unbind("SUPER + O")
hl.unbind("SUPER + N")
hl.unbind("SUPER + Slash")
hl.unbind("SUPER + K")
hl.unbind("SUPER + M")
hl.unbind("SUPER + J")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + BracketLeft")
hl.unbind("SUPER + BracketRight")
hl.unbind("SUPER + Semicolon")
hl.unbind("SUPER + Apostrophe")
hl.unbind("SUPER + ALT + Space")
hl.unbind("SUPER + D")
hl.unbind("SUPER + F")
hl.unbind("SUPER + P")
hl.unbind("CTRL + SUPER + S")
hl.unbind("ALT + Tab")
hl.unbind("SUPER + S")
hl.unbind("SUPER + L")
hl.unbind("SUPER + SHIFT + L")
hl.unbind("CTRL + SHIFT + ALT + SUPER + Delete")
hl.unbind("SUPER + SHIFT + N")
hl.unbind("SUPER + SHIFT + B")
hl.unbind("SUPER + SHIFT + P")
hl.unbind("SUPER + Return")
hl.unbind("SUPER + T")
hl.unbind("CTRL + ALT + T")
hl.unbind("SUPER + E")
hl.unbind("SUPER + W")
hl.unbind("SUPER + C")
hl.unbind("SUPER + SHIFT + W")
hl.unbind("SUPER + X")
hl.unbind("CTRL + SUPER + V")
hl.unbind("SUPER + I")
hl.unbind("SUPER + G")
hl.unbind("SUPER + SHIFT + M")
hl.unbind("SUPER + ALT + W")
hl.unbind("SUPER + Left")
hl.unbind("SUPER + Right")
hl.unbind("SUPER + Up")
hl.unbind("SUPER + Down")
hl.unbind("SUPER + ALT + F")
hl.unbind("SUPER + ALT + M")
hl.unbind("SUPER + ALT + S")
hl.unbind("SUPER + code:10")
hl.unbind("SUPER + code:11")
hl.unbind("SUPER + code:12")
hl.unbind("SUPER + code:13")
hl.unbind("SUPER + code:14")
hl.unbind("SUPER + code:15")
hl.unbind("SUPER + code:16")
hl.unbind("SUPER + code:17")
hl.unbind("SUPER + code:18")
hl.unbind("SUPER + code:19")
hl.unbind("SUPER + code:87")
hl.unbind("SUPER + code:88")
hl.unbind("SUPER + code:89")
hl.unbind("SUPER + code:83")
hl.unbind("SUPER + code:84")
hl.unbind("SUPER + code:85")
hl.unbind("SUPER + code:79")
hl.unbind("SUPER + code:80")
hl.unbind("SUPER + code:81")
hl.unbind("SUPER + code:90")
hl.unbind("XF86AudioNext")
hl.unbind("XF86AudioPrev")
hl.unbind("XF86AudioPlay")
hl.unbind("XF86AudioPause")
hl.unbind("CTRL + SUPER + R")

-- Shell config / keybinds
hl.bind("CTRL + SUPER + Slash",       hl.dsp.exec_cmd("xdg-open ~/.config/illogical-impulse/config.json"), { description = "Edit shell config" })
hl.bind("CTRL + SUPER + ALT + Slash", hl.dsp.exec_cmd("xdg-open ~/.config/hypr/custom/keybinds.lua"),     { description = "Edit user keybinds" })

-- Cheatsheet
hl.bind("SUPER + Apostrophe", hl.dsp.global("quickshell:cheatsheetToggle"), { description = "Toggle cheatsheet" })

-- Core apps
hl.bind("SUPER + Return",         hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd("warp-terminal"))
hl.bind("SUPER + B",              hl.dsp.exec_cmd(browser))
hl.bind("SUPER + Q",              hl.dsp.window.close())
hl.bind("SUPER + CTRL + Q",       hl.dsp.exec_cmd("hyprctl dispatch exit"))
hl.bind("SUPER + SHIFT + E",      hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + braceright",     hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + F",              hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + ALT + F",        hl.dsp.window.fullscreen({ mode = "maximized",  action = "toggle" }))
hl.bind("SUPER + SHIFT + F",      hl.dsp.window.fullscreen_state({ internal = 0, client = 1, action = "toggle" }))
hl.bind("SUPER + P",              hl.dsp.exec_cmd("hyprctl dispatch pseudo"))
hl.bind("SUPER + SHIFT + P",      hl.dsp.window.pin())
hl.bind("SUPER + R",              hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/toggle_float_center.sh"))
hl.bind("ALT + Tab",              hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/dispatch_warp.sh workspace previous"))
hl.bind("SUPER + SHIFT + Tab",    hl.dsp.exec_cmd("hyprctl dispatch cyclenext visible next hist"))

-- Master layout
hl.bind("SUPER + Plus",              hl.dsp.layout("mfact +0.05"))
hl.bind("SUPER + Minus",             hl.dsp.layout("mfact -0.05"))
hl.bind("SUPER + Backspace",         hl.dsp.layout("mfact exact 0.47142"))
hl.bind("SUPER + ALT + Backspace",   hl.dsp.layout("mfact exact 0.55"))
hl.bind("CTRL + SUPER + Backspace",  hl.dsp.layout("mfact exact 0.3544"))
hl.bind("SUPER + Left",              hl.dsp.layout("orientationnext"))
hl.bind("SUPER + Right",             hl.dsp.layout("orientationprev"))
hl.bind("SUPER + I",                 hl.dsp.layout("rollnext"))
hl.bind("SUPER + O",                 hl.dsp.layout("rollprev"))

-- Layout switch
hl.bind("SUPER + code:87",  hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh master"),    { passthrough = true })
hl.bind("CTRL + SUPER + U", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh master"),    { passthrough = true })
hl.bind("SUPER + code:88",  hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh dwindle"),   { passthrough = true })
hl.bind("CTRL + SUPER + I", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh dwindle"),   { passthrough = true })
hl.bind("SUPER + code:89",  hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh scrolling"), { passthrough = true })
hl.bind("CTRL + SUPER + O", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/switch_layout.sh scrolling"), { passthrough = true })

-- App shortcuts
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("betterbird"))
hl.bind("SUPER + A",         hl.dsp.exec_cmd("elecwhat"))
hl.bind("SUPER + D",         hl.dsp.exec_cmd("vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland"))
hl.bind("SUPER + ALT + S",   hl.dsp.exec_cmd('chromium --app="https://chat.openai.com"'))
hl.bind("SUPER + S",         hl.dsp.exec_cmd('chromium --app="https://gemini.google.com/app"'))
hl.bind("SUPER + T",         hl.dsp.exec_cmd('chromium --app="https://translate.google.com/?sl=en&tl=es&op=translate"'))
hl.bind("SUPER + ALT + M",   hl.dsp.exec_cmd("spotify --enable-features=UseOzonePlatform --ozone-platform=wayland"))
hl.bind("SUPER + E",         hl.dsp.exec_cmd('kitty --class "kitty-yazi" -e fish -c "yazi"'))
hl.bind("SUPER + SHIFT + U", hl.dsp.exec_cmd('kitty --class "kitty-update" -e fish -c "upd"'))

-- Restart QuickShell
hl.bind("CTRL + SUPER + R", hl.dsp.exec_cmd("pkill -x .quickshell-wra; qs -c $qsConfig &"))

-- Monitor scripts
hl.bind("SUPER + CTRL + F1", hl.dsp.exec_cmd("/home/javier/scripts/configure_monitors.sh 1monitor"))
hl.bind("SUPER + CTRL + F2", hl.dsp.exec_cmd("/home/javier/scripts/configure_monitors.sh pbp"))

-- Focus (hjkl)
hl.bind("SUPER + H", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_focus.sh l"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_focus.sh r"))
hl.bind("SUPER + K", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_focus.sh u"))
hl.bind("SUPER + J", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_focus.sh d"))

-- Workspace navigation (monitor-relative)
hl.bind("SUPER + Period", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/dispatch_warp.sh workspace m+1"))
hl.bind("SUPER + Comma",  hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/dispatch_warp.sh workspace m-1"))

-- Swap windows
hl.bind("SUPER + ALT + H", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_swap.sh l"))
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_swap.sh r"))
hl.bind("SUPER + ALT + K", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_swap.sh u"))
hl.bind("SUPER + ALT + J", hl.dsp.exec_cmd("~/.config/hypr/custom/scripts/smart_swap.sh d"))

-- Resize windows
hl.bind("SUPER + SHIFT + H", hl.dsp.window.resize({ x = -60, y = 0 }), { repeating = true })
hl.bind("SUPER + SHIFT + L", hl.dsp.window.resize({ x = 60,  y = 0 }), { repeating = true })
hl.bind("SUPER + SHIFT + K", hl.dsp.window.resize({ x = 0, y = -60 }), { repeating = true })
hl.bind("SUPER + SHIFT + J", hl.dsp.window.resize({ x = 0,  y = 60 }), { repeating = true })

-- Workspaces 1-10
for i = 1, 10 do
    local key = i == 10 and "0" or tostring(i)
    hl.bind("SUPER + " .. key,           hl.dsp.focus({ workspace = i }))
    hl.bind("SUPER + SHIFT + " .. key,   hl.dsp.window.move({ workspace = i }))
end

-- Workspaces 11-20
for i = 1, 10 do
    local key = i == 10 and "0" or tostring(i)
    hl.bind("CTRL + SUPER + " .. key, hl.dsp.focus({ workspace = i + 10 }))
end

hl.bind("SUPER + N",         hl.dsp.focus({ workspace = "emptym" }))
hl.bind("SUPER + SHIFT + N", hl.dsp.window.move({ workspace = "emptym" }))

-- Mouse drag/resize
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Media (Spotify)
hl.bind("SUPER + F6",    hl.dsp.exec_cmd("playerctl --player spotify previous"),   { locked = true })
hl.bind("SUPER + F7",    hl.dsp.exec_cmd("playerctl --player spotify play-pause"), { locked = true })
hl.bind("SUPER + F8",    hl.dsp.exec_cmd("playerctl --player spotify next"),       { locked = true })
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl --player spotify next"),       { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl --player spotify previous"),   { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl --player spotify play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl --player spotify play-pause"), { locked = true })
hl.bind("SUPER + F9",    hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- QuickShell
hl.bind("SUPER + SHIFT + Q", hl.dsp.global("quickshell:barDockToggle"),         { description = "Toggle bar/dock" })
hl.bind("SUPER + Z",         hl.dsp.global("quickshell:sidebarLeftToggle"),      { description = "Toggle left sidebar" })
hl.bind("SUPER + ALT + Z",   hl.dsp.global("quickshell:sidebarLeftToggleDetach"))
hl.bind("SUPER + X",         hl.dsp.global("quickshell:sidebarRightToggle"),     { description = "Toggle right sidebar" })
hl.bind("SUPER + G",         hl.dsp.global("quickshell:overlayToggle"),          { description = "Toggle overlay" })
hl.bind("CTRL + SUPER + L",  hl.dsp.global("quickshell:lock"))
hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd("qs -p ~/.config/quickshell/$qsConfig/settings.qml"))
hl.bind("CTRL + SUPER + F9", hl.dsp.exec_cmd("~/scripts/vm.sh"))
hl.bind("SUPER + SHIFT + Z", hl.dsp.global("quickshell:mediaModeToggle"),        { description = "Toggle media mode" })
hl.bind("SUPER + SHIFT + V", hl.dsp.global("quickshell:screenTranslate"))

-- Screenshot
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output -m DP-2"))
