# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

workspace=1,monitor:DP-2,default:true
# workspace=2,monitor:HDMI-A-5,default:true

windowrule = match:class .*, suppress_event maximize # You'll probably like this.
windowrule = match:title ^(Selector de Wallpapers)$, float on
# windowrule = match:title ^(Selector de Wallpapers)$, size 1600 800
windowrule = match:title ^(nmtui)$, float on
windowrule = match:title ^(update.sh)$, float on, size 1600 800
windowrule = match:title ^(Blender Animation Player)$, float on
windowrule = match:initial_title ^(.*Reminder.*)$, float on, size 60% 60%, center on
# windowrule = match:title ^(Calculator)$, float on
# windowrule = match:title ^(Calculator)$, size 400 600
windowrule = match:class (qalculate-gtk), float on
windowrule = match:title ^(.*Aseprite.*)$, tile on
# windowrule = match:initial_title ^(.*Spotify.*)$, opacity 0.90 0.90
# windowrule = match:class ^(discord|Spotify|kitty|WebCord|nemo|code|dev.warp.Warp|eu.betterbird.Betterbird|vesktop|neovide|ferdium|jetbrains.*)$, opacity 0.90 0.90
# windowrule = match:workspace name:special:translate, opacity 0.90 0.90
# windowrule = match:workspace name:special:openai, opacity 0.90 0.90
# windowrule = match:workspace name:special:mail, opacity 0.90 0.90
# windowrule = match:workspace name:special:special, opacity 0.90 0.90
# windowrule = match:class ^steam_app\d+$, fullscreen on
windowrule = match:class ^steam_app_\d+$, monitor DP-2
# windowrule = match:title ^()$, match:class ^(steam)$, move onscreen cursor
windowrule = match:class ^(chromium-chatgpt|chromium-translate)$, tile on
# windowrule = match:class ^(steam)$, tile on

# workspace=f[0],rounding:false,bordersize:0,gapsout:0
# workspace=f[1],rounding:false,bordersize:0,gapsout:0

layerrule = xray off, match:namespace ^quickshell.*
layerrule = blur off, match:namespace ^quickshell.*
layerrule = ignore_alpha 0.39, match:namespace ^quickshell.*

# windowrule = match:class (brave-browser), workspace 1
windowrule {
  name = brave-rules
  match:class = brave-browser

  workspace = 1
  fullscreen_state = 0 1
}

windowrule {
  name = zen-rules
  match:class = zen

  workspace = 1
  fullscreen_state = 0 1
}

windowrule {
  name = vesktop-rules
  match:class = vesktop

  workspace = 2
  fullscreen_state = 0 1
}

windowrule {
  name = waterfox-rules
  match:class = waterfox

  workspace = 5
  fullscreen_state = 0 1
}

windowrule {
  name = librewolf-rules
  match:class = librewolf

  workspace = 11
  fullscreen_state = 0 1
}

windowrule = match:class (elecwhat), workspace 2
windowrule = match:class (eu.betterbird.Betterbird), workspace 2
windowrule = match:class (steam), workspace 3
windowrule = match:class (net.lutris.Lutris), workspace 3
windowrule = match:class (heroic), workspace 3
# windowrule = match:class (kitty), workspace 5
windowrule = match:class (chrome-chat.openai.com__-Default), workspace 4
windowrule = match:class (chrome-gemini.google.com__app-Default), workspace 4
windowrule = match:title (quickshell), workspace 4
windowrule = match:title (Friends List), float on, center on
windowrule = match:class (hyprland-share-picker), float on, center on
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, move 3840 717
windowrule = match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$, size 1260 709

workspace = r[1-99], layout:master
# workspace = w[t1]f[-1], gapsout:5 1360 5 1360
