workspace = special:term, on-created-empty:kitty --class "kitty-special"
workspace = special:update, on-created-empty:kitty --class "kitty-update" -e fish -c "upd"
workspace = special:install, on-created-empty:kitty --class "kitty-install" -e fish -c "pkginstall"
workspace = special:uninstall, on-created-empty:kitty --class "kitty-uninstall" -e fish -c "pkgremove"
workspace = special:yazi, on-created-empty:kitty --class "kitty-yazi" -e fish -c "yazi"
workspace = special:btop, on-created-empty:kitty --class "kitty-btop" -e fish -c "btop"
workspace = special:spotify-term, on-created-empty:kitty --class "kitty-spotify" -e spotify_player
workspace = special:english, on-created-empty: kitty --class "kitty-english" -e fish -c "nvim /home/javier/Documents/ingles.txt"
workspace = special:translate, on-created-empty: chromium --app="https://translate.google.com/?sl=en&tl=es&op=translate"
# workspace = special:ferdium, on-created-empty: ferdium --ozone-platform=wayland --enable-features=UseOzonePlatform --enable-wayland-ime --wayland-text-input-version=3
# workspace = special:openai, on-created-empty: chromium --app="https://chat.openai.com"
# workspace = special:vesktop, on-created-empty: vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland 
workspace = special:spotify, on-created-empty: spotify --enable-features=UseOzonePlatform --ozone-platform=wayland
# workspace = special:betterbird, on-created-empty: betterbird
workspace = special:yt-music, on-created-empty: youtube-music --enable-features=UseOzonePlatform --ozone-platform=wayland

bind = Super, W, togglespecialworkspace
# bind = Super, A, togglespecialworkspace, ferdium
bind = Super, M, togglespecialworkspace, spotify
# bind = Super, S, togglespecialworkspace, openai
bind = Super+Alt, E, togglespecialworkspace, yazi
bind = Super+Alt, T, togglespecialworkspace, translate
bind = Super, ntilde, togglespecialworkspace, term
bind = Super+Shift, B, togglespecialworkspace, btop
bind = Super+Shift, W, movetoworkspace, special
bind = Super+Alt, W, movetoworkspacesilent, special
# bind = Super, T, togglespecialworkspace, betterbird
bind = Super+Alt, U, togglespecialworkspace, update
# bind = Super, Y, togglespecialworkspace, install
# bind = Super+Shift, Y, togglespecialworkspace, uninstall
# bind = Super+Shift, ntilde, togglespecialworkspace, english
# bind = Super, D, togglespecialworkspace, vesktop
# bind = Super+Shift, M, togglespecialworkspace, spotify-term
bind = Super+Shift, M, togglespecialworkspace, yt-music
