"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:yellow bg:none)[ ](bg:yellow fg:black)[](fg:yellow bg:none)\
$conda\
$docker_context\
$directory\
$package\
$git_branch\
$git_status\
${custom.git_end}\
$cmd_duration\
$fill\
${custom.prog_ver_start}\
$python$nodejs$java$golang\
${custom.prog_ver_end}\
$line_break\
$character
"""

add_newline = true

[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[❯](fg:red)"

[custom.prog_ver_start]
style = "fg:black bg:none"
symbol = ""
detect_files = ["pyproject.toml", ".python-version"]


[custom.prog_ver_end]
style = "fg:black bg:none"
symbol = ""
detect_files = ["pyproject.toml", ".python-version"]

[cmd_duration]
style = "fg:blue bg:none"
format = "[]($style)[  $duration](fg:black bg:blue)[]($style)"

[directory]
style = "fg:green bg:none"
format = "[]($style)[ 󰝰 $path ](fg:black bg:green)[]($style)"
truncation_length = 1
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󱔘"
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[fill]
symbol = " "

[conda]
style = "fg:color5 bg:none"
format = "[]($style)[ conda $environment ](fg:color0 bg:color5)[]($style)"

[docker_context]
style = "fg:color5 bg:none"
format = "[]($style)[ docker $environment ](fg:color0 bg:color5)[]($style)"

[package]
style = "fg:black bg:none"
format = "[]($style)[ $version ](fg:color0 bg:color4)[]($style)"

[git_branch]
symbol = ""
style = "fg:black bg:cyan"
format = '[](fg:cyan bg:none)[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:cyan"
format = '[$all_status$ahead_behind]($style)'
conflicted = "=$count "
untracked = "?$count "
modified = "!$count "
deleted = "✘$count "
staged = "+$count "
renamed = "»$count "
stashed = "*$count "
ahead = "⇡$count "
behind = "⇣$count "
diverged = "⇕ ⇣$behind_count ⇡$ahead_count "

[custom.git_end]
style = "fg:cyan bg:none"
symbol = ""
format = "[$symbol]($style)"
when = "git status 2>/dev/null; echo \\$?"
require_repo = true

[python]
symbol = ""
style = "fg:color0 bg:color4"
format = '[ [$symbol](fg:color7 bg:color4) $version ]($style)'

[golang]
symbol = ""
style = "fg:color0 bg:color4"
format = '[ $symbol $version ]($style)'

[nodejs]
symbol = "󰎙"
style = "fg:color0 bg:color4"
format = '[ $symbol $version ]($style)'

# [custom.angular]
# symbol = "󰚲"
# style = "fg:color0 bg:color4"
# format = '[ $symbol $output ]($style)'
# command = "jq -r '.dependencies[\"@angular/core\"]' 'package.json' | sed 's/[^0-9.]//g'"
# detect_files = ["angular.json", "package.json"]
